-- FR-RETENTION-3 — Email preview, controlled send, delivery tracking.
-- Hand-authored (NOT generated by `prisma migrate dev`).
--
-- Scope, exactly:
--   · outreach_messages        — the approved message for one audience
--   · email_delivery_attempts  — one attempt per delivery address
--   · email_provider_events    — append-only provider history (FOUNDATION ONLY)
--   · OutreachBatchStatus      — send lifecycle values appended
--
-- STATUS HONESTY: the provider is Resend, and this repository has no Resend
-- webhook handler. A returned message id proves the provider ACCEPTED the
-- message, not that it was delivered. DeliveryAttemptStatus therefore tops out
-- at `accepted`. email_provider_events exists so a future webhook can be
-- ingested safely; nothing writes to it in this checkpoint.
--
-- Deliberately NOT included: the parked PasswordResetToken work. This migration
-- must never create `password_reset_tokens`. It also creates nothing belonging
-- to Checkpoint 4+ (no rebooking_submissions, rebooking_opportunities,
-- campaign_contacts, outreach_executions).
--
-- Additive only: no existing table, column, constraint, or row is modified.
-- Enum values are appended, which PostgreSQL supports without rewriting rows.

-- ── enums ────────────────────────────────────────────────────────────────────
DO $$ BEGIN CREATE TYPE "OutreachMessageStatus" AS ENUM ('draft', 'approved', 'sending', 'sent', 'sent_with_issues', 'failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "DeliveryAttemptStatus" AS ENUM ('queued', 'accepted', 'failed', 'skipped_suppressed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "DeliveryFailureCategory" AS ENUM ('provider_rejected_recipient', 'provider_auth', 'transient_transport', 'invalid_address', 'unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ProviderEventType" AS ENUM ('delivered', 'bounced', 'complained', 'deferred'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Append the send-lifecycle values to the existing CP2 batch status enum.
ALTER TYPE "OutreachBatchStatus" ADD VALUE IF NOT EXISTS 'sending';
ALTER TYPE "OutreachBatchStatus" ADD VALUE IF NOT EXISTS 'completed';
ALTER TYPE "OutreachBatchStatus" ADD VALUE IF NOT EXISTS 'completed_with_issues';
ALTER TYPE "OutreachBatchStatus" ADD VALUE IF NOT EXISTS 'failed_before_send';

-- ── outreach_messages ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "outreach_messages" (
  "id"                 TEXT NOT NULL,
  "business_id"        TEXT NOT NULL,
  "outreach_batch_id"  TEXT NOT NULL,
  "subject"            TEXT NOT NULL,
  "html_body"          TEXT NOT NULL,
  "text_body"          TEXT NOT NULL,
  "version"            INTEGER NOT NULL DEFAULT 1,
  "status"             "OutreachMessageStatus" NOT NULL DEFAULT 'draft',
  "created_by_user_id" TEXT,
  "approved_at"        TIMESTAMP(3),
  "send_started_at"    TIMESTAMP(3),
  "send_completed_at"  TIMESTAMP(3),
  "created_at"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"         TIMESTAMP(3) NOT NULL,
  CONSTRAINT "outreach_messages_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "outreach_messages_business_id_id_key"
  ON "outreach_messages" ("business_id", "id");
-- One current message per audience in this checkpoint.
CREATE UNIQUE INDEX IF NOT EXISTS "outreach_messages_one_per_batch"
  ON "outreach_messages" ("outreach_batch_id");

ALTER TABLE "outreach_messages"
  DROP CONSTRAINT IF EXISTS "outreach_messages_business_id_fkey";
ALTER TABLE "outreach_messages"
  ADD CONSTRAINT "outreach_messages_business_id_fkey"
  FOREIGN KEY ("business_id") REFERENCES "businesses"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "outreach_messages"
  DROP CONSTRAINT IF EXISTS "outreach_messages_batch_fkey";
ALTER TABLE "outreach_messages"
  ADD CONSTRAINT "outreach_messages_batch_fkey"
  FOREIGN KEY ("business_id", "outreach_batch_id")
  REFERENCES "outreach_batches"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- A message cannot finish sending before it started.
ALTER TABLE "outreach_messages"
  DROP CONSTRAINT IF EXISTS "outreach_messages_send_window_check";
ALTER TABLE "outreach_messages"
  ADD CONSTRAINT "outreach_messages_send_window_check"
  CHECK ("send_completed_at" IS NULL OR "send_started_at" IS NOT NULL);

-- ── email_delivery_attempts ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "email_delivery_attempts" (
  "id"                    TEXT NOT NULL,
  "business_id"           TEXT NOT NULL,
  "outreach_batch_id"     TEXT NOT NULL,
  "outreach_recipient_id" TEXT NOT NULL,
  "outreach_message_id"   TEXT NOT NULL,
  "idempotency_key"       TEXT NOT NULL,
  "attempt_number"        INTEGER NOT NULL DEFAULT 1,
  "status"                "DeliveryAttemptStatus" NOT NULL DEFAULT 'queued',
  "provider_message_id"   TEXT,
  "accepted_at"           TIMESTAMP(3),
  "failed_at"             TIMESTAMP(3),
  "skipped_at"            TIMESTAMP(3),
  "failure_category"      "DeliveryFailureCategory",
  "failure_detail"        TEXT,
  "is_test"               BOOLEAN NOT NULL DEFAULT false,
  "created_at"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"            TIMESTAMP(3) NOT NULL,
  CONSTRAINT "email_delivery_attempts_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "email_delivery_attempts_business_id_id_key"
  ON "email_delivery_attempts" ("business_id", "id");
CREATE INDEX IF NOT EXISTS "email_delivery_attempts_batch_status_idx"
  ON "email_delivery_attempts" ("business_id", "outreach_batch_id", "status");

-- THE duplicate-prevention guarantee. The deterministic key is claimed inside
-- the send transaction, so two concurrent Send requests cannot both create an
-- attempt for the same recipient — the loser hits this constraint and yields.
CREATE UNIQUE INDEX IF NOT EXISTS "email_delivery_attempts_idempotency_key"
  ON "email_delivery_attempts" ("idempotency_key");

-- Belt and braces: at most one LIVE real attempt per (message, recipient).
--
-- `failed` is deliberately excluded from the constraint. A queued, accepted or
-- skipped attempt blocks any second send — that is the duplicate guarantee. But
-- a genuinely FAILED recipient must remain retryable, otherwise one transient
-- provider error would permanently lock that coordinator out of the send with
-- no way back. Excluding failed rows is what makes a future safe retry possible
-- while still making a duplicate delivery impossible.
--
-- Also partial on is_test, so repeated test sends to the tenant's own address
-- stay possible.
CREATE UNIQUE INDEX IF NOT EXISTS "email_delivery_attempts_one_live_per_recipient"
  ON "email_delivery_attempts" ("outreach_message_id", "outreach_recipient_id")
  WHERE NOT "is_test" AND "status" <> 'failed';

ALTER TABLE "email_delivery_attempts"
  DROP CONSTRAINT IF EXISTS "email_delivery_attempts_business_id_fkey";
ALTER TABLE "email_delivery_attempts"
  ADD CONSTRAINT "email_delivery_attempts_business_id_fkey"
  FOREIGN KEY ("business_id") REFERENCES "businesses"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "email_delivery_attempts"
  DROP CONSTRAINT IF EXISTS "email_delivery_attempts_message_fkey";
ALTER TABLE "email_delivery_attempts"
  ADD CONSTRAINT "email_delivery_attempts_message_fkey"
  FOREIGN KEY ("business_id", "outreach_message_id")
  REFERENCES "outreach_messages"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- Restrict: a delivery record must keep the recipient it describes.
ALTER TABLE "email_delivery_attempts"
  DROP CONSTRAINT IF EXISTS "email_delivery_attempts_recipient_fkey";
ALTER TABLE "email_delivery_attempts"
  ADD CONSTRAINT "email_delivery_attempts_recipient_fkey"
  FOREIGN KEY ("business_id", "outreach_recipient_id")
  REFERENCES "outreach_recipients"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── email_provider_events ────────────────────────────────────────────────────
-- Append-only. FOUNDATION ONLY: no webhook route exists in this checkpoint, so
-- nothing writes here. Deliberately not populated with invented events.
CREATE TABLE IF NOT EXISTS "email_provider_events" (
  "id"                  TEXT NOT NULL,
  "business_id"         TEXT NOT NULL,
  "delivery_attempt_id" TEXT NOT NULL,
  "provider_event_id"   TEXT,
  "event_type"          "ProviderEventType" NOT NULL,
  "occurred_at"         TIMESTAMP(3),
  "received_at"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "metadata"            JSONB,
  "created_at"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "email_provider_events_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "email_provider_events_business_attempt_idx"
  ON "email_provider_events" ("business_id", "delivery_attempt_id");

-- A replayed webhook must not double-record the same provider event. Partial
-- because the id is only present when the provider supplies one.
CREATE UNIQUE INDEX IF NOT EXISTS "email_provider_events_one_per_provider_event"
  ON "email_provider_events" ("business_id", "provider_event_id")
  WHERE "provider_event_id" IS NOT NULL;

ALTER TABLE "email_provider_events"
  DROP CONSTRAINT IF EXISTS "email_provider_events_business_id_fkey";
ALTER TABLE "email_provider_events"
  ADD CONSTRAINT "email_provider_events_business_id_fkey"
  FOREIGN KEY ("business_id") REFERENCES "businesses"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "email_provider_events"
  DROP CONSTRAINT IF EXISTS "email_provider_events_attempt_fkey";
ALTER TABLE "email_provider_events"
  ADD CONSTRAINT "email_provider_events_attempt_fkey"
  FOREIGN KEY ("business_id", "delivery_attempt_id")
  REFERENCES "email_delivery_attempts"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;
