-- FR-RETENTION-4 — Secure rebooking link, submission, revisions, opportunities.
-- Hand-authored (NOT generated by `prisma migrate dev`).
--
-- Scope, exactly:
--   · outreach_recipients                 — rebooking credential columns added
--   · rebooking_submissions               — one response thread per recipient
--   · rebooking_submission_revisions      — immutable snapshot per submit
--   · rebooking_submission_revision_orgs  — per-organization state per revision
--   · rebooking_opportunities             — durable record per (season, org)
--   · CoordinatorIntent                   — new enum
--   · RebookingOpportunityStatus          — new enum
--
-- TOKEN SECRECY: only "rebooking_token_hash" exists, and it holds SHA-256 of the
-- raw token. There is no plaintext token column anywhere in this migration, and
-- deliberately none on outreach_messages or email_delivery_attempts. A database
-- dump therefore cannot be replayed into working rebooking links.
--
-- The credential belongs to the DELIVERY RECIPIENT, not to a person. One inbox
-- may represent several durable contacts and several organizations, and we have
-- no way to know which of them opened the email — so the link authenticates the
-- address that was written to, and nothing more.
--
-- Deliberately NOT included: the parked PasswordResetToken work. This migration
-- must never create `password_reset_tokens`. It also creates nothing belonging
-- to Checkpoint 5+ (no campaign_contacts, no campaign_contact_access_grants, no
-- fundraiser_campaign rows, no scheduling).
--
-- Additive only: no existing table, column, constraint, or row is modified. The
-- columns added to outreach_recipients are all NULLABLE, so existing audience
-- rows remain valid without a backfill.

-- ── enums ────────────────────────────────────────────────────────────────────
-- `not_sure` is a real answer, not an absence of one. A respondent who does not
-- yet know who will coordinate must be able to say so without being forced into
-- a wrong yes/no.
DO $$ BEGIN CREATE TYPE "CoordinatorIntent" AS ENUM ('yes', 'no', 'not_sure'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- interested   — the respondent asked for it; the tenant has not decided yet
-- approved     — the tenant said yes; ready for a fundraiser to be created (CP5)
-- needs_review — the respondent CHANGED something the tenant had already
--                approved. A silent overwrite there would be the worst outcome.
-- canceled     — deselected by the respondent, or "Not this season" by the tenant
-- converted    — a fundraiser exists. Nothing in Checkpoint 4 sets this.
DO $$ BEGIN CREATE TYPE "RebookingOpportunityStatus" AS ENUM ('interested', 'approved', 'needs_review', 'canceled', 'converted'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── outreach_recipients · rebooking credential ───────────────────────────────
ALTER TABLE "outreach_recipients" ADD COLUMN IF NOT EXISTS "rebooking_token_hash"       TEXT;
ALTER TABLE "outreach_recipients" ADD COLUMN IF NOT EXISTS "rebooking_token_issued_at"  TIMESTAMP(3);
ALTER TABLE "outreach_recipients" ADD COLUMN IF NOT EXISTS "rebooking_token_expires_at" TIMESTAMP(3);
ALTER TABLE "outreach_recipients" ADD COLUMN IF NOT EXISTS "rebooking_token_revoked_at" TIMESTAMP(3);
-- Set when a respondent asks for a fresh link from an expired page. Surfaces to
-- the tenant as "Needs action"; nothing sends automatically.
ALTER TABLE "outreach_recipients" ADD COLUMN IF NOT EXISTS "refresh_requested_at"       TIMESTAMP(3);

-- Global (not tenant-scoped) because the hash is the lookup key on a public,
-- unauthenticated route: the URL carries no business identifier, so the digest
-- must be unambiguous across the whole table. Not partial and not needing to be
-- — PostgreSQL treats NULLs as distinct, so the vast majority of audience rows
-- that carry no credential never collide.
CREATE UNIQUE INDEX IF NOT EXISTS "outreach_recipients_rebooking_token_hash_key"
  ON "outreach_recipients" ("rebooking_token_hash");

-- A revoked or expired credential is still resolvable — the respondent must get
-- an honest "this link expired" page rather than a generic not-found. This index
-- exists so the tenant-side "needs a fresh link" queue stays cheap.
CREATE INDEX IF NOT EXISTS "outreach_recipients_refresh_requested_idx"
  ON "outreach_recipients" ("business_id", "refresh_requested_at")
  WHERE "refresh_requested_at" IS NOT NULL;

-- A credential cannot expire before it was issued.
ALTER TABLE "outreach_recipients"
  DROP CONSTRAINT IF EXISTS "outreach_recipients_rebooking_token_window_check";
ALTER TABLE "outreach_recipients"
  ADD CONSTRAINT "outreach_recipients_rebooking_token_window_check"
  CHECK (
    "rebooking_token_expires_at" IS NULL
    OR "rebooking_token_issued_at" IS NULL
    OR "rebooking_token_expires_at" > "rebooking_token_issued_at"
  );

-- ── rebooking_submissions ────────────────────────────────────────────────────
-- One durable response THREAD per delivery recipient. Editing a response appends
-- a revision to this thread; it never starts a second one.
CREATE TABLE IF NOT EXISTS "rebooking_submissions" (
  "id"                    TEXT NOT NULL,
  "business_id"           TEXT NOT NULL,
  "seasonal_offering_id"  TEXT NOT NULL,
  "outreach_recipient_id" TEXT NOT NULL,
  "current_revision"      INTEGER NOT NULL DEFAULT 0,
  "created_at"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"            TIMESTAMP(3) NOT NULL,
  CONSTRAINT "rebooking_submissions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_submissions_business_id_id_key"
  ON "rebooking_submissions" ("business_id", "id");
-- THE thread guarantee: two concurrent first-submits for the same link cannot
-- both create a thread. The loser retries against the winner's row.
CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_submissions_outreach_recipient_id_key"
  ON "rebooking_submissions" ("outreach_recipient_id");
CREATE INDEX IF NOT EXISTS "rebooking_submissions_business_offering_idx"
  ON "rebooking_submissions" ("business_id", "seasonal_offering_id");

ALTER TABLE "rebooking_submissions"
  DROP CONSTRAINT IF EXISTS "rebooking_submissions_business_id_fkey";
ALTER TABLE "rebooking_submissions"
  ADD CONSTRAINT "rebooking_submissions_business_id_fkey"
  FOREIGN KEY ("business_id") REFERENCES "businesses"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "rebooking_submissions"
  DROP CONSTRAINT IF EXISTS "rebooking_submissions_recipient_fkey";
ALTER TABLE "rebooking_submissions"
  ADD CONSTRAINT "rebooking_submissions_recipient_fkey"
  FOREIGN KEY ("business_id", "outreach_recipient_id")
  REFERENCES "outreach_recipients"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ── rebooking_submission_revisions ───────────────────────────────────────────
-- IMMUTABLE. Nothing in the application updates a revision after creation; a
-- changed answer becomes revision N+1. That is what lets the tenant see what was
-- said first and what changed, instead of only the latest state.
CREATE TABLE IF NOT EXISTS "rebooking_submission_revisions" (
  "id"                       TEXT NOT NULL,
  "business_id"              TEXT NOT NULL,
  "submission_id"            TEXT NOT NULL,
  "revision_number"          INTEGER NOT NULL,
  -- Response evidence, NOT authority to rewrite CRM identity. A respondent
  -- correcting their own name here never overwrites a FundraiserContact.
  "respondent_name"          TEXT,
  "respondent_email"         TEXT,
  "respondent_phone"         TEXT,
  "preferred_start_date"     TIMESTAMP(3),
  "alternate_start_date"     TIMESTAMP(3),
  "preferred_end_date"       TIMESTAMP(3),
  "participant_estimate"     INTEGER,
  "notes"                    TEXT,
  "contact_update_requested" BOOLEAN NOT NULL DEFAULT false,
  "idempotency_key"          TEXT NOT NULL,
  "created_at"               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "rebooking_submission_revisions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_submission_revisions_business_id_id_key"
  ON "rebooking_submission_revisions" ("business_id", "id");
-- A double-submitted form cannot produce two revisions.
CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_submission_revisions_idempotency_key"
  ON "rebooking_submission_revisions" ("idempotency_key");
-- Revision numbers are dense and gapless per thread; a concurrent second submit
-- collides here rather than silently overwriting revision N.
CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_submission_revisions_submission_number_key"
  ON "rebooking_submission_revisions" ("submission_id", "revision_number");

ALTER TABLE "rebooking_submission_revisions"
  DROP CONSTRAINT IF EXISTS "rebooking_submission_revisions_submission_fkey";
ALTER TABLE "rebooking_submission_revisions"
  ADD CONSTRAINT "rebooking_submission_revisions_submission_fkey"
  FOREIGN KEY ("business_id", "submission_id")
  REFERENCES "rebooking_submissions"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- Revision numbering starts at 1.
ALTER TABLE "rebooking_submission_revisions"
  DROP CONSTRAINT IF EXISTS "rebooking_submission_revisions_number_check";
ALTER TABLE "rebooking_submission_revisions"
  ADD CONSTRAINT "rebooking_submission_revisions_number_check"
  CHECK ("revision_number" >= 1);

-- A participant estimate is a count, and a negative count is not a lower bound —
-- it is a bug. Zero is allowed: "we don't know yet" arrives as NULL.
ALTER TABLE "rebooking_submission_revisions"
  DROP CONSTRAINT IF EXISTS "rebooking_submission_revisions_participants_check";
ALTER TABLE "rebooking_submission_revisions"
  ADD CONSTRAINT "rebooking_submission_revisions_participants_check"
  CHECK ("participant_estimate" IS NULL OR "participant_estimate" >= 0);

-- Timing is a preference, not a booking, so almost anything is allowed — except
-- a window that ends before it starts, which can only be a mistake.
ALTER TABLE "rebooking_submission_revisions"
  DROP CONSTRAINT IF EXISTS "rebooking_submission_revisions_window_check";
ALTER TABLE "rebooking_submission_revisions"
  ADD CONSTRAINT "rebooking_submission_revisions_window_check"
  CHECK (
    "preferred_end_date" IS NULL
    OR "preferred_start_date" IS NULL
    OR "preferred_end_date" >= "preferred_start_date"
  );

-- ── rebooking_submission_revision_orgs ───────────────────────────────────────
-- One row per REPRESENTED organization per revision — SELECTED OR NOT. Keeping
-- the unselected ones is what lets the tenant read "Cedar Ridge sat this season
-- out" instead of watching a row quietly vanish between revisions.
CREATE TABLE IF NOT EXISTS "rebooking_submission_revision_orgs" (
  "id"                 TEXT NOT NULL,
  "business_id"        TEXT NOT NULL,
  "revision_id"        TEXT NOT NULL,
  "customer_id"        TEXT NOT NULL,
  -- Denormalized on purpose: this is what the organization was CALLED at the
  -- moment of the response. A later rename in the CRM must not rewrite history.
  "organization_name"  TEXT NOT NULL,
  "selected"           BOOLEAN NOT NULL DEFAULT false,
  "coordinator_intent" "CoordinatorIntent" NOT NULL DEFAULT 'not_sure',
  -- Captured when the respondent says someone else will coordinate. EVIDENCE
  -- ONLY — it grants no portal access and creates no CampaignContact.
  "coordinator_name"   TEXT,
  "coordinator_email"  TEXT,
  "org_notes"          TEXT,
  "created_at"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "rebooking_submission_revision_orgs_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_submission_revision_orgs_revision_customer_key"
  ON "rebooking_submission_revision_orgs" ("revision_id", "customer_id");
CREATE INDEX IF NOT EXISTS "rebooking_submission_revision_orgs_business_customer_idx"
  ON "rebooking_submission_revision_orgs" ("business_id", "customer_id");

ALTER TABLE "rebooking_submission_revision_orgs"
  DROP CONSTRAINT IF EXISTS "rebooking_submission_revision_orgs_revision_fkey";
ALTER TABLE "rebooking_submission_revision_orgs"
  ADD CONSTRAINT "rebooking_submission_revision_orgs_revision_fkey"
  FOREIGN KEY ("business_id", "revision_id")
  REFERENCES "rebooking_submission_revisions"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- Restrict: a response snapshot must keep the organization it describes.
ALTER TABLE "rebooking_submission_revision_orgs"
  DROP CONSTRAINT IF EXISTS "rebooking_submission_revision_orgs_customer_fkey";
ALTER TABLE "rebooking_submission_revision_orgs"
  ADD CONSTRAINT "rebooking_submission_revision_orgs_customer_fkey"
  FOREIGN KEY ("business_id", "customer_id")
  REFERENCES "customers"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── rebooking_opportunities ──────────────────────────────────────────────────
-- One durable, REOPENABLE record per (season, organization). Deselecting cancels
-- it; reselecting reopens THIS row rather than creating a second one.
CREATE TABLE IF NOT EXISTS "rebooking_opportunities" (
  "id"                    TEXT NOT NULL,
  "business_id"           TEXT NOT NULL,
  "seasonal_offering_id"  TEXT NOT NULL,
  "customer_id"           TEXT NOT NULL,
  "outreach_recipient_id" TEXT NOT NULL,
  "submission_id"         TEXT NOT NULL,
  "source_revision_id"    TEXT NOT NULL,
  "organization_name"     TEXT NOT NULL,
  "status"                "RebookingOpportunityStatus" NOT NULL DEFAULT 'interested',
  "coordinator_intent"    "CoordinatorIntent" NOT NULL DEFAULT 'not_sure',
  "coordinator_name"      TEXT,
  "coordinator_email"     TEXT,
  "preferred_start_date"  TIMESTAMP(3),
  "alternate_start_date"  TIMESTAMP(3),
  "participant_estimate"  INTEGER,
  "notes"                 TEXT,
  -- CP5 conversion target. Checkpoint 4 never creates a campaign, so this stays
  -- NULL and carries no foreign key yet.
  "campaign_id"           TEXT,
  "canceled_at"           TIMESTAMP(3),
  "reopened_at"           TIMESTAMP(3),
  "created_at"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"            TIMESTAMP(3) NOT NULL,
  CONSTRAINT "rebooking_opportunities_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_opportunities_business_id_id_key"
  ON "rebooking_opportunities" ("business_id", "id");

-- ONE organization = ONE future fundraiser per season. This is the constraint
-- that makes reselection REOPEN rather than duplicate, even when two submits
-- race. It is intentionally NOT partial: a canceled opportunity still occupies
-- the slot, because reopening it is the correct behaviour, not creating a twin.
CREATE UNIQUE INDEX IF NOT EXISTS "rebooking_opportunities_one_per_org_per_season"
  ON "rebooking_opportunities" ("business_id", "seasonal_offering_id", "customer_id");

CREATE INDEX IF NOT EXISTS "rebooking_opportunities_business_status_idx"
  ON "rebooking_opportunities" ("business_id", "status");

ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_business_id_fkey";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_business_id_fkey"
  FOREIGN KEY ("business_id") REFERENCES "businesses"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_offering_fkey";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_offering_fkey"
  FOREIGN KEY ("business_id", "seasonal_offering_id")
  REFERENCES "seasonal_offerings"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_customer_fkey";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_customer_fkey"
  FOREIGN KEY ("business_id", "customer_id")
  REFERENCES "customers"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_recipient_fkey";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_recipient_fkey"
  FOREIGN KEY ("business_id", "outreach_recipient_id")
  REFERENCES "outreach_recipients"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_submission_fkey";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_submission_fkey"
  FOREIGN KEY ("business_id", "submission_id")
  REFERENCES "rebooking_submissions"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- Restrict: the opportunity must keep the exact revision it was derived from,
-- so "why does this say 40 participants?" always has an answer.
ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_source_revision_fkey";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_source_revision_fkey"
  FOREIGN KEY ("business_id", "source_revision_id")
  REFERENCES "rebooking_submission_revisions"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- A canceled opportunity must record when it was canceled, and a live one must
-- not claim to be canceled. This is what keeps the tenant list truthful.
ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_canceled_consistency_check";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_canceled_consistency_check"
  CHECK (
    ("status" = 'canceled' AND "canceled_at" IS NOT NULL)
    OR ("status" <> 'canceled' AND "canceled_at" IS NULL)
  );

ALTER TABLE "rebooking_opportunities"
  DROP CONSTRAINT IF EXISTS "rebooking_opportunities_participants_check";
ALTER TABLE "rebooking_opportunities"
  ADD CONSTRAINT "rebooking_opportunities_participants_check"
  CHECK ("participant_estimate" IS NULL OR "participant_estimate" >= 0);
