-- FR-COORD-SEC-1B · Secure coordinator credential exchange
--
-- This migration creates ONE thing: the coordinator session table. It adds no
-- column to any existing table, drops nothing, and writes no row.
--
-- WHY THE TABLE EXISTS
-- The coordinator credential used to travel in the URL path and was re-sent on
-- every request, so one portal visit wrote the secret into Vercel's request log
-- a dozen times over. The fix moves the credential into the URL fragment, which
-- browsers never transmit, and exchanges it ONCE for an opaque session cookie.
-- This table is the server side of that session.
--
-- Only sha256(secret) is stored. The raw cookie value lives in the
-- coordinator's browser and nowhere else, so a database disclosure cannot be
-- replayed as a live session — the same reasoning already used for
-- outreach_recipients.rebooking_token_hash.
--
-- WHAT IS DELIBERATELY *NOT* HERE
-- The companion schema change removes `@default(cuid())` from
-- fundraiser_campaigns.portal_token, and there is no SQL for it on purpose.
-- Prisma's `cuid()` default is generated by the CLIENT, not by PostgreSQL: the
-- baseline declares the column as plain `"portal_token" TEXT`, and Production
-- reports `column_default = null` today, before this migration. An
-- `ALTER COLUMN ... DROP DEFAULT` here would therefore be a no-op that merely
-- looked like a security fix. The real protection is the Prisma schema edit plus
-- the fact that every runtime create path already passes
-- mintCoordinatorPortalToken() explicitly — both of which are asserted by
-- tests/coordinatorSecurity.test.ts rather than by a database column default.

-- ── the session table ───────────────────────────────────────────────────────
CREATE TABLE "coordinator_sessions" (
    "id" TEXT NOT NULL,
    "campaign_id" TEXT NOT NULL,
    -- sha256 of the opaque cookie secret, hex. The raw value is never stored.
    "session_hash" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Fixed lifetime, stamped at creation. No sliding expiry in v1.
    "expires_at" TIMESTAMP(3) NOT NULL,
    -- Set by explicit logout and by portal_token rotation.
    "revoked_at" TIMESTAMP(3),
    "last_used_at" TIMESTAMP(3),

    CONSTRAINT "coordinator_sessions_pkey" PRIMARY KEY ("id")
);

-- UNIQUE so validating a cookie is one indexed probe, and so two sessions can
-- never collide on a single digest.
CREATE UNIQUE INDEX "coordinator_sessions_session_hash_key"
    ON "coordinator_sessions"("session_hash");

-- Revoking every session for a campaign (rotation, admin reset) is a range scan.
CREATE INDEX "coordinator_sessions_campaign_id_idx"
    ON "coordinator_sessions"("campaign_id");

-- Expiry sweeps.
CREATE INDEX "coordinator_sessions_expires_at_idx"
    ON "coordinator_sessions"("expires_at");

-- Deleting a campaign takes its sessions with it: a session has no meaning
-- without the campaign it authorises, and leaving orphans would be a dangling
-- credential.
ALTER TABLE "coordinator_sessions" ADD CONSTRAINT "coordinator_sessions_campaign_id_fkey"
    FOREIGN KEY ("campaign_id") REFERENCES "fundraiser_campaigns"("id") ON DELETE CASCADE ON UPDATE CASCADE;
