-- AlterTable
ALTER TABLE "bundle_contents" ADD COLUMN     "mult_serves_2" DOUBLE PRECISION NOT NULL DEFAULT 2.0,
ADD COLUMN     "mult_serves_5" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
ADD COLUMN     "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
