/**
 * INV-D — what it means for an invoice to have been PAID.
 *
 * THE ONE RULE
 *
 * `PAID` records that a human at the tenant confirmed they received the money,
 * and it may only be written together with the facts that make that claim
 * checkable: HOW it arrived and WHEN. A status with no settlement facts is what
 * Production has today — five PAID invoices that cannot say when they were paid,
 * and six invoices that all read `payment_method = 'check'` including one that
 * has never been paid at all. That is the untruth this module exists to stop.
 *
 *     clicking Mark Paid with no method/date  -> rejected, stays outstanding
 *     order moved to production_ready         -> NOT payment (see PART I below)
 *     invoice emailed and delivered           -> still outstanding (INV-C)
 *     owner confirms the check cleared        -> PAID, with method + date
 *
 * WHAT FREEZERIQ IS NOT CLAIMING
 *
 * `square` here means "the tenant told us it came in through Square". FreezerIQ
 * makes no Square API call, reads no settlement report, and reconciles nothing.
 * It is a recorded human statement, exactly like `check` is, and neither is
 * evidence from a payment processor. Nothing in this module should ever be
 * presented to a tenant as verified or confirmed by Square.
 *
 * Likewise `check` collects a check NUMBER at most. No routing number, no
 * account number, no check image, no bank name. Those are not asked for, not
 * validated, and not stored — the field is a memo line, not a bank record.
 *
 * WHAT IS DELIBERATELY ABSENT
 *
 * No partial payments, no payment schedule, no processor-fee allocation, no
 * refunds, no bank feed, no QuickBooks sync. An invoice is outstanding or it is
 * settled. Anything finer is a different product decision and would need its own
 * schema; faking it on top of a single boolean-ish status would produce numbers
 * that look precise and are not.
 */

import { OUTSTANDING_INVOICE_STATUSES } from './invoiceSendTruth';

// ───────────────────────────────────────────────────────────────────────────
// METHOD
// ───────────────────────────────────────────────────────────────────────────

/**
 * The only two ways a fundraiser organization actually pays this tenant.
 *
 * Narrower than the `payment_method` column, which stays free text because
 * ordinary manual invoices legitimately use it for an EXPECTED method on the
 * printed PDF (venmo, ach, cash and so on). A *settlement* is stricter: it is a
 * claim that money arrived, so it may only name a channel the owner confirmed
 * is real for fundraisers. Widening this list is a business decision, not a
 * typo-fix.
 */
export const SETTLEMENT_PAYMENT_METHODS = ['square', 'check'] as const;

export type SettlementPaymentMethod = typeof SETTLEMENT_PAYMENT_METHODS[number];

/** Owner-facing wording. Neither label implies FreezerIQ verified anything. */
export const SETTLEMENT_METHOD_LABELS: Record<SettlementPaymentMethod, string> = {
    square: 'Square',
    check: 'Check',
};

export function isSettlementPaymentMethod(value: unknown): value is SettlementPaymentMethod {
    return typeof value === 'string'
        && (SETTLEMENT_PAYMENT_METHODS as readonly string[]).includes(value);
}

// ───────────────────────────────────────────────────────────────────────────
// ELIGIBILITY
// ───────────────────────────────────────────────────────────────────────────

/**
 * Which invoices may be settled — and it is exactly the set that counts as
 * outstanding.
 *
 * That is not a coincidence worth hiding behind a duplicated array, so this
 * reuses INV-C's list directly. The invariant is: **you can only settle a debt
 * you are actually claiming.** If the two lists ever drift apart, Total
 * Outstanding and Mark Paid would disagree about what is owed, and one of the
 * two numbers on the owner's screen would be wrong.
 *
 *   DRAFT     rejected — generated by closeout, still under review. Nobody has
 *             been asked for this money yet, so "they paid it" cannot be true.
 *             Send it first; then settle it.
 *   PENDING   allowed — issued, unpaid.
 *   SENT      allowed — issued, unpaid. The normal fundraiser path.
 *   OVERDUE   allowed — issued, unpaid, late.
 *   PAID      rejected here and handled as idempotent success by the endpoint,
 *             which returns the settlement facts already stored rather than
 *             overwriting them with a second click's values.
 *   CANCELED  rejected — withdrawn, never collectable.
 */
export const SETTLEABLE_INVOICE_STATUSES = OUTSTANDING_INVOICE_STATUSES;

export function isSettleableInvoiceStatus(status: unknown): boolean {
    return typeof status === 'string'
        && (SETTLEABLE_INVOICE_STATUSES as readonly string[]).includes(status);
}

// ───────────────────────────────────────────────────────────────────────────
// DATE HANDLING
// ───────────────────────────────────────────────────────────────────────────

/**
 * A settlement date is a CALENDAR DAY, anchored at 12:00 UTC.
 *
 * The owner knows the day a check arrived, not the second. Storing the day is
 * therefore the honest granularity — but a bare `new Date('2026-08-24')` parses
 * to UTC midnight, and any viewer west of UTC then renders it as the 23rd.
 * Anchoring at noon moves that cliff as far away as a single instant can: the
 * date reads back correctly under LOCAL rendering for every offset from UTC-11
 * through UTC+11. (No anchor covers the full real range of -12..+14, which spans
 * 26 hours; +12 and beyond — New Zealand, Fiji — would roll to the next day.
 * FreezerIQ's tenants are US-based, at UTC-4..UTC-8.)
 *
 * That cliff is defence in depth rather than the primary mechanism: every
 * comparison and every render in this module uses UTC getters, so the stored
 * date and the displayed date agree regardless of where the viewer sits. The
 * anchor is what keeps that true if anything ever reaches for a local getter.
 */
export function calendarDateToUtcNoon(ymd: string): Date | null {
    const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(ymd.trim());
    if (!m) return null;
    const year = Number(m[1]);
    const month = Number(m[2]);
    const day = Number(m[3]);
    if (month < 1 || month > 12 || day < 1 || day > 31) return null;
    const date = new Date(Date.UTC(year, month - 1, day, 12, 0, 0, 0));
    // Rejects real-calendar impossibilities such as 2026-02-30, which Date
    // would otherwise silently roll forward into March.
    if (date.getUTCFullYear() !== year
        || date.getUTCMonth() !== month - 1
        || date.getUTCDate() !== day) {
        return null;
    }
    return date;
}

/** Renders a stored settlement date back as the calendar day it represents. */
export function utcNoonToCalendarDate(value: Date): string {
    const y = value.getUTCFullYear();
    const m = String(value.getUTCMonth() + 1).padStart(2, '0');
    const d = String(value.getUTCDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
}

/**
 * Nothing was paid before FreezerIQ's tenants were operating. A date earlier
 * than this is a typo (`0226`, `1026`), not history.
 *
 * The floor is deliberately NOT the invoice's own created_at: an organization
 * can hand over a check at the closeout meeting, before the invoice is
 * generated, and rejecting that would force the owner to record a date they
 * know to be wrong.
 */
export const SETTLEMENT_DATE_FLOOR_ISO = '2020-01-01';

/**
 * One day of slack on the future bound.
 *
 * The server does not know the tenant's timezone. At 8pm US Central it is
 * already tomorrow in UTC, so a strict "not after today, UTC" test would reject
 * a perfectly legitimate same-day settlement — or, flipped the other way,
 * reject "today" for a tenant east of UTC. A single day of tolerance makes the
 * check generous in the harmless direction while still catching a fat-fingered
 * year or month.
 */
export const SETTLEMENT_FUTURE_SLACK_DAYS = 1;

export type SettlementValidation =
    | {
        ok: true;
        value: {
            method: SettlementPaymentMethod;
            paidAt: Date;
            reference: string | null;
        };
    }
    | { ok: false; error: string };

/** Longest reference we will store. A check number or a Square id, not an essay. */
export const SETTLEMENT_REFERENCE_MAX_LENGTH = 100;

/**
 * Normalises the optional reference: trims, collapses whitespace, strips control
 * characters, caps length, and turns blank into null.
 *
 * Deliberately does NOT pattern-match for bank details. A check number and a
 * Square transaction id have no shape in common, so any regex strong enough to
 * catch a routing number would also reject legitimate references — and a false
 * reject here would push the owner to record no reference at all, which is the
 * worse outcome. The contract "do not collect banking details" is met by not
 * asking for them: there is no routing field, no account field, and the UI label
 * says check number or Square reference.
 */
export function normalizeSettlementReference(value: unknown): string | null {
    if (typeof value !== 'string') return null;
    const cleaned = value
        // eslint-disable-next-line no-control-regex
        .replace(/[\x00-\x1f\x7f]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .slice(0, SETTLEMENT_REFERENCE_MAX_LENGTH);
    return cleaned.length > 0 ? cleaned : null;
}

/**
 * The whole settlement input rule, with no I/O so it can be tested directly.
 *
 * `now` is injected rather than read from the clock so the future-date bound is
 * deterministic under test.
 */
export function validateSettlement(
    input: { method?: unknown; paidAt?: unknown; reference?: unknown },
    now: Date,
): SettlementValidation {
    const method = typeof input.method === 'string' ? input.method.trim().toLowerCase() : input.method;
    if (!isSettlementPaymentMethod(method)) {
        return { ok: false, error: 'Select how this invoice was paid: Square or Check.' };
    }

    if (typeof input.paidAt !== 'string' || input.paidAt.trim().length === 0) {
        return { ok: false, error: 'Enter the date this payment was received.' };
    }
    const paidAt = calendarDateToUtcNoon(input.paidAt);
    if (!paidAt) {
        return { ok: false, error: 'Enter the payment date as a real calendar date (YYYY-MM-DD).' };
    }

    const floor = calendarDateToUtcNoon(SETTLEMENT_DATE_FLOOR_ISO)!;
    if (paidAt.getTime() < floor.getTime()) {
        return { ok: false, error: 'That payment date is too far in the past to be correct.' };
    }

    const latest = new Date(now.getTime() + SETTLEMENT_FUTURE_SLACK_DAYS * 24 * 60 * 60 * 1000);
    if (paidAt.getTime() > latest.getTime()) {
        return { ok: false, error: 'A payment date cannot be in the future.' };
    }

    return {
        ok: true,
        value: { method, paidAt, reference: normalizeSettlementReference(input.reference) },
    };
}

// ───────────────────────────────────────────────────────────────────────────
// CORRECTING A MISTAKEN PAYMENT
// ───────────────────────────────────────────────────────────────────────────

/**
 * Does this invoice carry durable INV-D settlement truth?
 *
 * All three facts must be present, because all three are what the correction
 * action gives back. An invoice that cannot say WHEN it was paid was not settled
 * through this system, and the correction path must not pretend it can undo
 * something it never recorded.
 */
export function hasDurableSettlement(invoice: {
    status?: unknown;
    paid_at?: unknown;
    payment_method?: unknown;
}): boolean {
    if (invoice?.status !== 'PAID') return false;
    // Deliberately redundant with the parse check below — `new Date(String(null))`
    // is already Invalid Date — but stated explicitly because "no recorded payment
    // date" is the single most important reason this function says no, and it
    // should not be something a reader has to derive from coercion rules.
    if (invoice?.paid_at === null || invoice?.paid_at === undefined) return false;
    const when = invoice.paid_at instanceof Date ? invoice.paid_at : new Date(String(invoice.paid_at));
    if (Number.isNaN(when.getTime())) return false;
    return isSettlementPaymentMethod(invoice?.payment_method);
}

/**
 * A PAID invoice from before INV-D: real money, unknown date.
 *
 * The five in Production are exactly this. They must NOT be correctable through
 * the ordinary Undo Payment action: the action's contract is "clear the recorded
 * settlement facts and return the invoice to its unpaid state", and for these
 * there are no recorded facts to clear. Running it would not correct a mistake,
 * it would delete a true historical payment and replace it with an outstanding
 * debt the organization does not owe.
 *
 * They are left exactly as they are. No cleanup, no backfill, no guessed dates.
 */
export function isLegacyUnrecordedPayment(invoice: { status?: unknown; paid_at?: unknown }): boolean {
    return invoice?.status === 'PAID'
        && (invoice?.paid_at === null || invoice?.paid_at === undefined);
}

export type UnsettledStatus = 'SENT' | 'OVERDUE' | 'PENDING';

/**
 * The status an invoice truthfully returns to when a mistaken payment is undone.
 *
 * This is DERIVED, not stored, and that is safe because of an invariant that
 * holds across the whole codebase:
 *
 *   DRAFT is written by exactly one place — INV-B closeout — which always sets
 *   campaign_id. SENT is written by exactly one place — INV-C's send route —
 *   which can only transition an invoice it finds in DRAFT. Therefore DRAFT and
 *   SENT imply campaign-linked, and a NON-campaign invoice can only ever have
 *   been PENDING or OVERDUE before it was settled.
 *
 * So:
 *   campaign-linked  -> SENT.    It had to be sent to become settleable, and a
 *                                fundraiser invoice that is unpaid again is an
 *                                issued, outstanding invoice — not a draft.
 *   otherwise        -> OVERDUE if its due date has passed, else PENDING. This
 *                      is the invoice's truthful unpaid state NOW rather than a
 *                      reconstruction of which of the two it was before.
 *
 * The invariant is load-bearing, so tests assert it directly: if manual invoices
 * ever become sendable, those tests fail and this rule must be revisited before
 * it can start quietly erasing an issued state.
 */
export function resolveUnsettledStatus(
    invoice: { campaign_id?: unknown; due_date?: unknown },
    now: Date,
): UnsettledStatus {
    if (typeof invoice?.campaign_id === 'string' && invoice.campaign_id.length > 0) {
        return 'SENT';
    }
    if (invoice?.due_date) {
        const due = invoice.due_date instanceof Date ? invoice.due_date : new Date(String(invoice.due_date));
        if (!Number.isNaN(due.getTime()) && due.getTime() < now.getTime()) return 'OVERDUE';
    }
    return 'PENDING';
}

/** Fields the correction action clears. Named once so the route and tests agree. */
export const SETTLEMENT_FACT_FIELDS = ['paid_at', 'payment_method', 'payment_reference'] as const;

// ───────────────────────────────────────────────────────────────────────────
// "PAID THIS MONTH"
// ───────────────────────────────────────────────────────────────────────────

/**
 * Was this invoice settled inside the current calendar month?
 *
 * A NULL `paid_at` is NOT counted, and that is the point rather than an
 * oversight. The five historical PAID invoices carry no payment date, because
 * nobody knows what those dates were. Counting them into whatever month someone
 * happens to be looking at would invent revenue for that month; assigning them
 * to their created_at would invent it for a different one. Excluding them states
 * the truth: those payments are real, and when they landed is unknown.
 *
 * The visible consequence is that "Paid This Month" reads $0.00 until a real
 * settlement is recorded through the settlement endpoint. That is correct.
 */
export function isPaidInCurrentMonth(paidAt: unknown, now: Date): boolean {
    if (paidAt === null || paidAt === undefined || paidAt === '') return false;
    const when = paidAt instanceof Date ? paidAt : new Date(String(paidAt));
    if (Number.isNaN(when.getTime())) return false;
    return when.getUTCFullYear() === now.getUTCFullYear()
        && when.getUTCMonth() === now.getUTCMonth();
}

/**
 * Sum of invoices actually settled this calendar month.
 *
 * Requires BOTH `status === 'PAID'` and a `paid_at` inside the month. Status
 * alone was the old rule, which summed every PAID invoice ever recorded and
 * labelled the result "Paid This Month" — on Production that reported $8,274.15
 * of payments from months earlier as though they had arrived this month.
 */
export function sumPaidThisMonth(
    invoices: Array<{ status?: unknown; total_amount?: unknown; paid_at?: unknown }>,
    now: Date,
): number {
    const total = invoices.reduce((sum, inv) => {
        if (inv?.status !== 'PAID') return sum;
        if (!isPaidInCurrentMonth(inv?.paid_at, now)) return sum;
        const amount = Number(inv?.total_amount);
        return Number.isFinite(amount) ? sum + amount : sum;
    }, 0);
    return Math.round((total + Number.EPSILON) * 100) / 100;
}
