/**
 * INV-C — what it means for a fundraiser invoice to have been SENT.
 *
 * THE ONE RULE
 *
 * `SENT` records that FreezerIQ actually handed the message to its configured
 * email provider and the provider accepted it. Nothing weaker earns that word:
 *
 *     opening the compose dialog      -> still DRAFT
 *     viewing or downloading the PDF  -> still DRAFT
 *     clicking Send, provider errors  -> still DRAFT
 *     clicking Send in safety mode    -> still DRAFT
 *
 * That last one is the case most likely to be got wrong, so it is stated as its
 * own rule rather than left implicit. app/api/email/send/route.ts returns
 * `{ success: true, mocked: true }` when EMAIL_LIVE is not exactly 'true' — a
 * SUCCESSFUL response for a message that was only logged. Treating that as SENT
 * would tell a tenant their coordinator has an invoice that was never posted.
 * The repository has been burned by exactly this shape before: that same route's
 * safety branch used to advance a customer's pipeline status for mail that never
 * left the building, and the comment there now explains why it stopped.
 *
 * WHY NO SCHEMA
 *
 * INV-C's contract is a STATUS transition, and `InvoiceStatus.SENT` already
 * exists from INV-A. There is deliberately no `sent_at` column: `updated_at` is
 * `@updatedAt`, so any later edit silently overwrites it, which would make it a
 * timestamp that lies rather than a record. If send-time reporting is wanted
 * later it needs a real column, and that is a decision to take on purpose — not
 * a field to fake out of the one that happens to be nearby.
 *
 * SENT IS NOT PAID. This module never produces PAID, and INV-C never writes it.
 */

/** The provider outcome, as the server observed it. */
export interface ProviderSendOutcome {
    /** The route returned a 2xx and no provider-level error. */
    ok: boolean;
    /** The send was simulated — EMAIL_LIVE was not exactly 'true'. */
    mocked: boolean;
    /** Provider message id, when a real send produced one. */
    providerId?: string | null;
    /** Operator-facing reason a send did not happen. Never shown raw to a customer. */
    error?: string | null;
}

export type InvoiceSendDecision =
    | { markSent: true; status: 'SENT'; reason: 'provider_accepted' }
    | { markSent: false; status: 'DRAFT'; reason: 'mocked' | 'provider_failed' };

/**
 * The whole truth rule, in one place, with no I/O so it can be tested directly.
 *
 * Only a real, accepted send advances the invoice. Everything else leaves it in
 * DRAFT so the tenant can try again and the list keeps telling them the truth.
 */
export function decideInvoiceSendStatus(outcome: ProviderSendOutcome): InvoiceSendDecision {
    if (outcome.mocked) {
        return { markSent: false, status: 'DRAFT', reason: 'mocked' };
    }
    if (!outcome.ok) {
        return { markSent: false, status: 'DRAFT', reason: 'provider_failed' };
    }
    return { markSent: true, status: 'SENT', reason: 'provider_accepted' };
}

/**
 * Is a real send configured, or is this environment in safety mode?
 *
 * Mirrors app/api/email/send/route.ts exactly — `EMAIL_LIVE === 'true'` and a
 * key present — so the two paths cannot drift into disagreeing about whether a
 * message actually goes out.
 */
export function isLiveEmailConfigured(env: {
    RESEND_API_KEY?: string;
    EMAIL_LIVE?: string;
}): boolean {
    return Boolean(env.RESEND_API_KEY) && env.EMAIL_LIVE === 'true';
}

/** Statuses INV-C is allowed to write. PAID and settlement belong to INV-D. */
export const INV_C_WRITABLE_STATUSES = ['SENT'] as const;

/**
 * Financial facts frozen onto a generated fundraiser invoice at closeout.
 *
 * The generic invoice PUT passes body fields straight to Prisma, so without this
 * a tenant could rewrite the gross, the organization's share or the tax on an
 * invoice INV-B had already computed and the owner had already accepted — and
 * the printed document would then disagree with the campaign's frozen
 * settlement_total. These are preserved from the stored row for any invoice that
 * has a campaign_id.
 */
export const CAMPAIGN_INVOICE_FROZEN_FIELDS = [
    'total_amount',
    'tax_amount',
    'fundraiser_profit_percent',
    'fundraiser_profit_amount',
    'items',
] as const;

/**
 * True when this invoice's financial facts were generated by closeout and must
 * not be edited through the generic invoice API.
 */
export function isGeneratedFundraiserInvoice(invoice: { campaign_id?: unknown }): boolean {
    return typeof invoice?.campaign_id === 'string' && invoice.campaign_id.length > 0;
}

// ───────────────────────────────────────────────────────────────────────────
// RECEIVABLES — what "Total Outstanding" counts
// ───────────────────────────────────────────────────────────────────────────

/**
 * Statuses that represent money genuinely owed to the tenant right now.
 *
 * The distinction that matters is ISSUED vs NOT ISSUED, not paid vs unpaid:
 *
 *   DRAFT     excluded — generated by closeout but still under review. Nobody
 *             has been asked for it yet, so counting it would inflate the
 *             receivable with an amount the tenant has not committed to.
 *   SENT      INCLUDED — issued and unpaid. This is the case the old
 *             PENDING-only filter got wrong: a real receivable was invisible.
 *   OVERDUE   INCLUDED — still outstanding, just late.
 *   PENDING   INCLUDED — unchanged.
 *   PAID      excluded — collected.
 *   CANCELED  excluded — never collectable.
 *
 * SENT being in this list is emphatically NOT a payment claim; it is the
 * opposite. An invoice counts as outstanding precisely BECAUSE it was issued
 * and has not been paid.
 */
export const OUTSTANDING_INVOICE_STATUSES = ['PENDING', 'SENT', 'OVERDUE'] as const;

export function isOutstandingInvoiceStatus(status: unknown): boolean {
    return typeof status === 'string'
        && (OUTSTANDING_INVOICE_STATUSES as readonly string[]).includes(status);
}

/**
 * Total currently owed to the tenant, to the cent.
 *
 * `total_amount` arrives as a Prisma Decimal serialised to a string, so each
 * value is coerced individually and the sum rounded once at the end rather than
 * relying on float addition to land clean.
 */
export function sumOutstandingInvoices(
    invoices: Array<{ status?: unknown; total_amount?: unknown }>,
): number {
    const total = invoices.reduce((sum, inv) => {
        if (!isOutstandingInvoiceStatus(inv?.status)) return sum;
        const amount = Number(inv?.total_amount);
        return Number.isFinite(amount) ? sum + amount : sum;
    }, 0);
    return Math.round((total + Number.EPSILON) * 100) / 100;
}
