-- INV-A · Fundraiser invoice foundation — PART 2 of 2: structural DDL.
--
-- Hand-written. NOT generated by prisma migrate dev: a read-only diff of the
-- current working schema against Production produces ~36 statements of
-- pre-existing unrelated drift (password_reset_tokens creation, an
-- orders.canceled_at type change, six NOT NULL repairs, constraint renames).
-- None of that belongs to INV-A and none of it appears below.
--
-- PRE-EXISTING DRIFT DELIBERATELY NOT TOUCHED HERE:
--   PasswordResetToken / password_reset_tokens (parked, absent in Production)
--   orders.canceled_at (timestamptz in Production, timestamp in schema)
--   storefront_configs + delivery_zones nullability
--   FR-RETENTION constraint names
--   delivery_zones.id default
--
-- ORDER RELATION: orders.invoice_id and orders_invoice_id_key are UNCHANGED.
-- Fundraiser campaign invoices do not link Orders through invoice_id; the
-- campaign linkage lives on invoices.campaign_id instead.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Per-campaign organization share.
--    PERCENT (25.00), not a fraction (0.25) — matches invoices.fundraiser_profit_percent
--    so INV-B's freeze-copy needs no unit conversion.
--    NOT NULL DEFAULT 20.00 backfills every existing campaign in this one
--    statement: no backfill script, and "every campaign has a share" becomes a
--    database invariant rather than a convention.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "fundraiser_campaigns"
  ADD COLUMN IF NOT EXISTS "org_share_percent" DECIMAL(5,2) NOT NULL DEFAULT 20.00;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Range guard, 0.00–100.00 inclusive.
--    Drop-then-add is the house idiom (see the FR-RETENTION migrations) so the
--    statement is re-runnable. This is the ONLY new NOT NULL / CHECK in INV-A.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "fundraiser_campaigns"
  DROP CONSTRAINT IF EXISTS "fundraiser_campaigns_org_share_percent_check";

ALTER TABLE "fundraiser_campaigns"
  ADD CONSTRAINT "fundraiser_campaigns_org_share_percent_check"
  CHECK ("org_share_percent" >= 0.00 AND "org_share_percent" <= 100.00);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Campaign linkage on the invoice.
--    Nullable: every existing invoice stays valid with campaign_id NULL, and
--    ordinary manual invoices keep it NULL forever.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "invoices"
  ADD COLUMN IF NOT EXISTS "campaign_id" TEXT;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Invoice -> campaign FK, ON DELETE RESTRICT.
--    Evidence for RESTRICT over SET NULL: no runtime path hard-deletes a
--    campaign (no fundraiserCampaign.delete anywhere, no DELETE handler under
--    app/api/campaigns), and the parent customer FK is already RESTRICT with an
--    application-level guard refusing deletion of an org that owns campaigns.
--    So RESTRICT constrains nothing that happens today, while making an
--    invoice's campaign identity permanent. CASCADE is explicitly wrong here:
--    deleting a campaign must never delete a financial record.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "invoices"
  DROP CONSTRAINT IF EXISTS "invoices_campaign_id_fkey";

ALTER TABLE "invoices"
  ADD CONSTRAINT "invoices_campaign_id_fkey"
  FOREIGN KEY ("campaign_id") REFERENCES "fundraiser_campaigns"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. THE idempotency guarantee: at most ONE invoice per campaign, forever.
--    Partial (WHERE campaign_id IS NOT NULL) so unlimited ordinary invoices
--    with NULL campaign_id coexist — Postgres never dedupes NULLs.
--    Deliberately NOT filtered on status: a CANCELED invoice keeps its slot, so
--    a campaign has ONE invoice lifecycle and corrections happen in place. The
--    invoice PUT handler already supports full in-place correction.
--    This is the FN-guardrail-approved shape ("compound (business_id, ...) or a
--    partial index"); a compound form is unavailable because
--    fundraiser_campaigns carries no business_id column.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS "invoices_one_per_campaign"
  ON "invoices" ("campaign_id")
  WHERE "campaign_id" IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Generation provenance, at INVOICE level only.
--    Deliberately not per-item: invoice_items have no stable identity (the PUT
--    handler deletes and recreates every row on each edit), so a per-row flag
--    would silently reset on first edit and read as authoritative while being
--    wrong. NULL on every ordinary manual invoice.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "invoices"
  ADD COLUMN IF NOT EXISTS "generated_at" TIMESTAMP(3);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Serving-size snapshot on invoice lines.
--    NULLABLE with NO default, unlike order_items.variant_size which is
--    NOT NULL DEFAULT 'serves_5'. A manual line ("Delivery fee") has no serving
--    size and must not be fabricated as serves_5. Existing rows become NULL,
--    which is the truthful value for them.
--    Reuses the existing "VariantSize" enum; no new type is created.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "invoice_items"
  ADD COLUMN IF NOT EXISTS "variant_size" "VariantSize";
