-- INV-A · Fundraiser invoice foundation — PART 1 of 2: enum values only.
--
-- WHY THIS IS ITS OWN MIGRATION
--   ALTER TYPE ... ADD VALUE cannot run inside a transaction block on older
--   PostgreSQL, and Prisma wraps each migration in one. Isolating the two enum
--   additions here keeps the structural DDL in Part 2 transactional and
--   re-runnable. Part 2 must be applied AFTER this file.
--
-- SCOPE GUARANTEE
--   This migration touches the InvoiceStatus type and nothing else. It creates
--   no table, alters no column, and must never create password_reset_tokens.
--
-- REVERSIBILITY
--   Enum values cannot be dropped without rebuilding the type. These two are
--   additive and inert until INV-B writes DRAFT, so leaving them in place on a
--   rollback of Part 2 is harmless.

-- DRAFT: generated by INV-B, not yet reviewed. Claims nothing of anyone.
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'DRAFT';

-- SENT: deliberately sent to the coordinator by a human (INV-C).
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'SENT';
