-- FR-RETENTION-0R + 1B-1 — hand-authored migration (NOT generated by `prisma migrate dev`).
--
-- Scope, exactly:
--   0R  · fundraiser_campaigns.customer_id  ON DELETE CASCADE -> RESTRICT
--         (campaign history must survive normal organization lifecycle)
--   1B-1· composite parent key on customers, plus three durable-contact tables
--
-- Deliberately NOT included: the parked PasswordResetToken work. This migration
-- must never create `password_reset_tokens`.
--
-- Additive except the single FK rule change; no column is dropped, no row is
-- modified, no data is deleted.

-- ── 0R · campaign-history deletion protection ────────────────────────────────
ALTER TABLE "fundraiser_campaigns"
  DROP CONSTRAINT IF EXISTS "fundraiser_campaigns_customer_id_fkey";

ALTER TABLE "fundraiser_campaigns"
  ADD CONSTRAINT "fundraiser_campaigns_customer_id_fkey"
  FOREIGN KEY ("customer_id") REFERENCES "customers"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── 1B-1 · composite tenant parent key ───────────────────────────────────────
-- Lets tenant-scoped children reference (business_id, customer_id) so Postgres
-- enforces same-business ownership structurally rather than in service code.
CREATE UNIQUE INDEX IF NOT EXISTS "customers_business_id_id_key"
  ON "customers" ("business_id", "id");

-- ── 1B-1 · enums ─────────────────────────────────────────────────────────────
DO $$ BEGIN CREATE TYPE "IdentityStatus" AS ENUM ('provisional', 'confirmed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ContactSource" AS ENUM ('backfill', 'tenant', 'coordinator_link', 'import'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ContactPointType" AS ENUM ('email', 'phone'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ContactPointLabel" AS ENUM ('work', 'personal', 'mobile', 'office', 'other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ArchiveReason" AS ENUM ('inactive', 'duplicate', 'left_organization', 'tenant_request'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "RelationshipRole" AS ENUM ('coordinator', 'relationship_contact', 'billing', 'other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "RelationshipEndReason" AS ENUM ('replaced', 'left', 'tenant_ended'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 1B-1 · fundraiser_contacts (durable person identity) ─────────────────────
CREATE TABLE IF NOT EXISTS "fundraiser_contacts" (
  "id"                TEXT NOT NULL,
  "business_id"       TEXT NOT NULL,
  "display_name"      TEXT NOT NULL,
  "identity_status"   "IdentityStatus" NOT NULL DEFAULT 'provisional',
  "needs_review"      BOOLEAN NOT NULL DEFAULT false,
  "review_reason"     TEXT,
  "history_starts_at" TIMESTAMP(3),
  "source"            "ContactSource" NOT NULL DEFAULT 'backfill',
  "archived_at"       TIMESTAMP(3),
  "archive_reason"    "ArchiveReason",
  "created_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"        TIMESTAMP(3) NOT NULL,
  CONSTRAINT "fundraiser_contacts_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "fundraiser_contacts_business_id_id_key"
  ON "fundraiser_contacts" ("business_id", "id");
CREATE INDEX IF NOT EXISTS "fundraiser_contacts_business_id_archived_at_idx"
  ON "fundraiser_contacts" ("business_id", "archived_at");
CREATE INDEX IF NOT EXISTS "fundraiser_contacts_business_id_needs_review_idx"
  ON "fundraiser_contacts" ("business_id", "needs_review");

ALTER TABLE "fundraiser_contacts"
  ADD CONSTRAINT "fundraiser_contacts_business_id_fkey"
  FOREIGN KEY ("business_id") REFERENCES "businesses"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ── 1B-1 · fundraiser_contact_points (append-only address/phone history) ─────
CREATE TABLE IF NOT EXISTS "fundraiser_contact_points" (
  "id"                  TEXT NOT NULL,
  "business_id"         TEXT NOT NULL,
  "contact_id"          TEXT NOT NULL,
  "type"                "ContactPointType" NOT NULL,
  "label"               "ContactPointLabel" NOT NULL DEFAULT 'work',
  "value"               TEXT NOT NULL,
  "normalized_value"    TEXT NOT NULL,
  "is_primary"          BOOLEAN NOT NULL DEFAULT true,
  "is_current"          BOOLEAN NOT NULL DEFAULT true,
  "is_shared_inbox"     BOOLEAN NOT NULL DEFAULT false,
  "valid_from"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "valid_to"            TIMESTAMP(3),
  "verified_at"         TIMESTAMP(3),
  "invalidated_at"      TIMESTAMP(3),
  "invalidation_reason" TEXT,
  "source"              "ContactSource" NOT NULL DEFAULT 'backfill',
  "created_at"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"          TIMESTAMP(3) NOT NULL,
  CONSTRAINT "fundraiser_contact_points_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "fundraiser_contact_points_business_id_normalized_value_idx"
  ON "fundraiser_contact_points" ("business_id", "normalized_value");
CREATE INDEX IF NOT EXISTS "fundraiser_contact_points_contact_id_type_is_current_idx"
  ON "fundraiser_contact_points" ("contact_id", "type", "is_current");

-- Exactly one PRIMARY CURRENT point per (contact, type); unlimited secondaries.
-- Partial unique index — not expressible as a Prisma @@unique.
CREATE UNIQUE INDEX IF NOT EXISTS "fundraiser_contact_points_one_primary_current"
  ON "fundraiser_contact_points" ("contact_id", "type")
  WHERE "is_primary" AND "is_current" AND "valid_to" IS NULL;

-- No duplicate current value of the same type on one contact.
CREATE UNIQUE INDEX IF NOT EXISTS "fundraiser_contact_points_one_current_value"
  ON "fundraiser_contact_points" ("contact_id", "type", "normalized_value")
  WHERE "is_current";

ALTER TABLE "fundraiser_contact_points"
  ADD CONSTRAINT "fundraiser_contact_points_business_id_contact_id_fkey"
  FOREIGN KEY ("business_id", "contact_id")
  REFERENCES "fundraiser_contacts"("business_id", "id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ── 1B-1 · fundraiser_organization_contacts (person ↔ org relationship) ──────
CREATE TABLE IF NOT EXISTS "fundraiser_organization_contacts" (
  "id"                      TEXT NOT NULL,
  "business_id"             TEXT NOT NULL,
  "contact_id"              TEXT NOT NULL,
  "customer_id"             TEXT NOT NULL,
  "role"                    "RelationshipRole" NOT NULL DEFAULT 'coordinator',
  "is_primary_relationship" BOOLEAN NOT NULL DEFAULT true,
  "started_at"              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ended_at"                TIMESTAMP(3),
  "ended_reason"            "RelationshipEndReason",
  "source"                  "ContactSource" NOT NULL DEFAULT 'backfill',
  "tenant_notes"            TEXT,
  "created_at"              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"              TIMESTAMP(3) NOT NULL,
  CONSTRAINT "fundraiser_organization_contacts_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "fundraiser_organization_contacts_business_id_customer_id_idx"
  ON "fundraiser_organization_contacts" ("business_id", "customer_id");
CREATE INDEX IF NOT EXISTS "fundraiser_organization_contacts_business_id_contact_id_idx"
  ON "fundraiser_organization_contacts" ("business_id", "contact_id");

-- One ACTIVE relationship per (contact, organization). Ended rows are retained
-- forever, so replacing a coordinator never deletes the predecessor.
CREATE UNIQUE INDEX IF NOT EXISTS "fundraiser_organization_contacts_one_active"
  ON "fundraiser_organization_contacts" ("contact_id", "customer_id")
  WHERE "ended_at" IS NULL;

-- History-bearing: RESTRICT, so a contact or organization holding relationship
-- history cannot be hard-deleted.
ALTER TABLE "fundraiser_organization_contacts"
  ADD CONSTRAINT "fundraiser_organization_contacts_business_id_contact_id_fkey"
  FOREIGN KEY ("business_id", "contact_id")
  REFERENCES "fundraiser_contacts"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "fundraiser_organization_contacts"
  ADD CONSTRAINT "fundraiser_organization_contacts_business_id_customer_id_fkey"
  FOREIGN KEY ("business_id", "customer_id")
  REFERENCES "customers"("business_id", "id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- CHECK: a relationship cannot end before it starts.
ALTER TABLE "fundraiser_organization_contacts"
  DROP CONSTRAINT IF EXISTS "fundraiser_organization_contacts_dates_check";
ALTER TABLE "fundraiser_organization_contacts"
  ADD CONSTRAINT "fundraiser_organization_contacts_dates_check"
  CHECK ("ended_at" IS NULL OR "ended_at" >= "started_at");
